# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8e768a92df68f7560c7c17ea59ffd75a52de9cdff6245a418abd4f417bb6e7dad61c8164414e4be887354b6a781f768959bad65833efab5d7d1d7f307f66e6

test:
  secret_key_base: a2663f29959740a2b3e202f7f54f76db598f3caf10959b7483ffe795f520d9f10efa0a6823f57b1a6c77d4bc51ffbd459db2f96eb7b1ea345c3606415afd566e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
